/* Auto-extracted from index.html — do not edit manually */

export const ATTRACTION_DATA = [
  // ── NORTH VIETNAM ──────────────────────────────────────────────
  {id:'ATT-N-001',region:'north',type:'museum',name:'Vietnam Museum of Ethnology',dest:'Hanoi',
   hours:'Tue–Sun 08:30–17:30',closed:'Monday',admission:'40,000 VND / ~$2',duration:90,
   best_time:'Morning (09:00–11:00)',crowd:'Moderate; quietest weekday mornings',
   book_req:false,seasonal:'No seasonal closures',
   notes:'One of Vietnam\'s finest museums. Outdoor exhibits close in heavy rain. Allow extra time for outdoor folk houses.',
   alert:'CLOSED MONDAYS'},
  {id:'ATT-N-002',region:'north',type:'landmark',name:'Ho Chi Minh Mausoleum',dest:'Hanoi',
   hours:'Tue–Thu, Sat–Sun 07:30–10:30 (summer) / 08:00–11:00 (winter)',closed:'Monday & Friday ALWAYS + Sep–Nov maintenance',admission:'Free',duration:60,
   best_time:'Early (07:30 open)',crowd:'Very busy on weekends; go at opening',
   book_req:false,seasonal:'CLOSED Sep–Nov for annual maintenance',
   notes:'Smart dress required. No shorts, sleeveless, hats. Bags stored at entrance. Solemn silence maintained.',
   alert:'CLOSED Mon & Fri + CLOSED Sep–Nov'},
  {id:'ATT-N-003',region:'north',type:'museum',name:'Vietnam National Museum of History',dest:'Hanoi',
   hours:'Tue–Sun 08:00–17:00',closed:'Monday',admission:'40,000 VND',duration:75,
   best_time:'Morning',crowd:'Light to moderate',book_req:false,
   seasonal:'No seasonal closures',notes:'Two buildings (ancient & modern). Good A/C. Allow 75 mins for both buildings.',alert:'CLOSED MONDAYS'},
  {id:'ATT-N-004',region:'north',type:'museum',name:'Vietnam Museum of Fine Arts',dest:'Hanoi',
   hours:'Tue–Sun 08:30–17:00',closed:'Monday',admission:'40,000 VND',duration:60,
   best_time:'Morning (avoid lunch hour)',crowd:'Usually quiet',book_req:false,
   seasonal:'No seasonal closures',notes:'3 floors. Folk art, lacquerware, sculpture. Often overlooked by tourists — excellent for art lovers.',alert:'CLOSED MONDAYS'},
  {id:'ATT-N-005',region:'north',type:'museum',name:'Women\'s Museum of Vietnam',dest:'Hanoi',
   hours:'Tue–Sun 08:00–17:00',closed:'Monday',admission:'30,000 VND',duration:45,
   best_time:'Any time',crowd:'Usually quiet',book_req:false,
   seasonal:'No seasonal closures',notes:'Fascinating exhibits on women\'s roles in Vietnamese history and war. Hidden gem in Old Quarter.',alert:'CLOSED MONDAYS'},
  {id:'ATT-N-006',region:'north',type:'museum',name:'Vietnam Military History Museum',dest:'Hanoi',
   hours:'Tue–Sun 08:00–17:00 (closed 11:30–13:00)',closed:'Monday',admission:'40,000 VND',duration:60,
   best_time:'Morning',crowd:'Moderate; busier on weekends',book_req:false,
   seasonal:'Outdoor exhibits affected in heavy rain',notes:'Features B-52 wreckage, military hardware. Closed for lunch 11:30–13:00 daily.',alert:'CLOSED MONDAYS + LUNCH 11:30–13:00'},
  {id:'ATT-N-007',region:'north',type:'museum',name:'Hoa Lo Prison Museum (Hanoi Hilton)',dest:'Hanoi',
   hours:'Daily 08:00–17:00',closed:'No regular closure',admission:'30,000 VND',duration:45,
   best_time:'Morning (before tour groups arrive)',crowd:'Busy 09:30–12:00',book_req:false,
   seasonal:'No seasonal closures',notes:'Open daily — good backup if Mausoleum is closed. Emotional and powerful. Guides highly recommended.',alert:'OPEN DAILY'},
  {id:'ATT-N-008',region:'north',type:'museum',name:'Museum of the Vietnamese Revolution',dest:'Hanoi',
   hours:'Tue–Sun 08:00–12:00, 14:00–17:00',closed:'Monday + lunch break',admission:'20,000 VND',duration:45,
   best_time:'Morning or afternoon',crowd:'Very light',book_req:false,
   seasonal:'No seasonal closures',notes:'Chronological exhibits from 1930–1975 revolution. Often combined with History Museum nearby.',alert:'CLOSED MONDAYS'},
  {id:'ATT-N-009',region:'north',type:'heritage',name:'Hoan Kiem Lake & Ngoc Son Temple',dest:'Hanoi',
   hours:'Temple 08:00–18:00 daily',closed:'None',admission:'30,000 VND (temple)',duration:45,
   best_time:'Early morning (06:30–08:00) or evening',crowd:'Busy at all times; quietest pre-8am',book_req:false,
   seasonal:'No seasonal closures',notes:'Lake always accessible. Temple on island requires entrance fee. Morning exercise culture best observed 06:00–07:30.',alert:'OPEN DAILY'},
  {id:'ATT-N-010',region:'north',type:'museum',name:'Vietnam Museum of Nature',dest:'Hanoi',
   hours:'Tue–Sun 08:30–17:00',closed:'Monday',admission:'30,000 VND',duration:45,
   best_time:'Morning',crowd:'Usually very quiet',book_req:false,
   seasonal:'No closures',notes:'Small museum covering geology, flora, fauna of Vietnam. Less visited — very pleasant for nature lovers.',alert:'CLOSED MONDAYS'},
  // HALONG / QUANG NINH
  {id:'ATT-N-011',region:'north',type:'heritage',name:'Ha Long Bay UNESCO Site',dest:'Halong Bay',
   hours:'Cruise departures 08:00–12:00',closed:'None but may suspend in typhoon season (Jul–Oct)',admission:'Per cruise package',duration:1440,
   best_time:'Nov–Apr (dry season, clear skies)',crowd:'Busy year-round; less Nov–Jan',book_req:true,
   seasonal:'Strong winds Oct; typhoon risk Jul–Sep. Some caves close Nov–Mar.',notes:'Book cruise 4+ weeks in advance in high season. Kayaking at Luon Cave best at low tide.',alert:'BOOK IN ADVANCE · CHECK WEATHER SEP–OCT'},
  {id:'ATT-N-012',region:'north',type:'museum',name:'Quang Ninh Museum',dest:'Halong Bay',
   hours:'Tue–Sun 08:00–17:00',closed:'Monday',admission:'Free',duration:45,
   best_time:'Morning',crowd:'Very light',book_req:false,
   seasonal:'No closures',notes:'Modern museum covering geology and history of Quang Ninh province. Excellent architecture.',alert:'CLOSED MONDAYS'},
  // NINH BINH
  {id:'ATT-N-013',region:'north',type:'heritage',name:'Trang An Scenic Landscape Complex',dest:'Ninh Binh',
   hours:'Daily 07:00–17:00',closed:'None',admission:'200,000 VND',duration:180,
   best_time:'Morning (07:00–10:00 before tour buses)',crowd:'Busy 09:00–14:00; very crowded weekends',book_req:false,
   seasonal:'Can flood Sep–Oct; beautiful but misty in winter',notes:'3-hour boat circuit. No motorised boats. Allow 3 hours. Avoid peak hours. Bring sun protection.',alert:'ARRIVE EARLY — BUSY BY 09:30'},
  {id:'ATT-N-014',region:'north',type:'museum',name:'Hoa Lu Ancient Capital',dest:'Ninh Binh',
   hours:'Daily 07:00–17:30',closed:'None',admission:'20,000 VND',duration:60,
   best_time:'Morning',crowd:'Light to moderate',book_req:false,
   seasonal:'No closures',notes:'First capital of Vietnam. Two well-preserved temples (Dinh and Le dynasties). Often paired with Trang An.',alert:'OPEN DAILY'},
  // SAPA
  {id:'ATT-N-015',region:'north',type:'museum',name:'Sapa Museum',dest:'Sapa',
   hours:'Daily 07:30–11:30, 13:30–17:30',closed:'None officially but irregular hours',admission:'Free',duration:30,
   best_time:'Morning',crowd:'Light',book_req:false,
   seasonal:'Fog common Nov–Mar; very cold Dec–Feb',notes:'Small but informative on ethnic minority cultures. Worth 30 mins before trekking. Irregular hours — call ahead.',alert:'VERIFY HOURS BEFORE VISITING'},

  // ── CENTRAL VIETNAM ────────────────────────────────────────────
  {id:'ATT-C-001',region:'central',type:'museum',name:'Museum of Royal Fine Arts (Hue)',dest:'Hue',
   hours:'Daily 07:00–17:30',closed:'None',admission:'40,000 VND',duration:60,
   best_time:'Morning',crowd:'Moderate',book_req:false,
   seasonal:'No seasonal closures',notes:'Located inside the Hue Citadel complex. Features imperial furniture, porcelain, royal objects. Combine with Citadel visit.',alert:'OPEN DAILY'},
  {id:'ATT-C-002',region:'central',type:'heritage',name:'Hue Imperial Citadel (Forbidden Purple City)',dest:'Hue',
   hours:'Daily 07:00–17:30 (summer) / 07:00–17:00 (winter)',closed:'None',admission:'200,000 VND',duration:180,
   best_time:'Early morning (07:00–09:00)',crowd:'Very busy 09:00–13:00; calmer after 14:30',book_req:false,
   seasonal:'Flooding risk Sep–Nov; check conditions',notes:'UNESCO. Allow 3 hours for full citadel. Hire electric cart for elderly/mobility limited guests. Audio guide available.',alert:'OPEN DAILY · FLOOD RISK SEP–NOV'},
  {id:'ATT-C-003',region:'central',type:'museum',name:'Hue Museum of History',dest:'Hue',
   hours:'Tue–Sun 07:00–17:30',closed:'Monday',admission:'20,000 VND',duration:45,
   best_time:'Morning',crowd:'Very light',book_req:false,
   seasonal:'No seasonal closures',notes:'Good context for the Citadel visit. Covers Nguyen Dynasty artefacts. Often skipped by tourists — worthwhile.',alert:'CLOSED MONDAYS'},
  {id:'ATT-C-004',region:'central',type:'museum',name:'Hue Museum of Traditional Huế Medicine',dest:'Hue',
   hours:'Mon–Sat 07:30–11:30, 13:30–17:00',closed:'Sunday',admission:'Free',duration:30,
   best_time:'Morning',crowd:'Very quiet',book_req:false,
   seasonal:'No closures',notes:'Niche but fascinating for wellness-oriented guests. Traditional herbal remedies and royal medicine.',alert:'CLOSED SUNDAYS'},
  {id:'ATT-C-005',region:'central',type:'heritage',name:'My Son Sanctuary (Cham Ruins)',dest:'Hoi An & Da Nang',
   hours:'Daily 06:30–17:00 (no entry after 16:30)',closed:'None but check monsoon season',admission:'150,000 VND',duration:120,
   best_time:'07:00–09:00 (beat crowds + heat)',crowd:'Very busy 09:00–13:00; quieter after 14:30',book_req:false,
   seasonal:'Avoid midday Jun–Aug (extreme heat). Some paths close Oct–Nov (flooding)',notes:'UNESCO. No entry after 16:30. Early morning essential in summer. Electric buggy available. Bring water.',alert:'NO ENTRY AFTER 16:30 · ARRIVE EARLY IN SUMMER'},
  {id:'ATT-C-006',region:'central',type:'museum',name:'Museum of Cham Sculpture (Da Nang)',dest:'Hoi An & Da Nang',
   hours:'Daily 07:00–17:00',closed:'None',admission:'60,000 VND',duration:60,
   best_time:'Morning or afternoon',crowd:'Light to moderate',book_req:false,
   seasonal:'No seasonal closures',notes:'Outstanding collection of Cham artefacts — best in the world. Essential companion to My Son visit. Well-curated, good A/C.',alert:'OPEN DAILY'},
  {id:'ATT-C-007',region:'central',type:'museum',name:'Hoi An Museum of History and Culture',dest:'Hoi An & Da Nang',
   hours:'Daily 08:00–17:00',closed:'None',admission:'Covered by Ancient Town ticket',duration:30,
   best_time:'Morning',crowd:'Moderate in town centre',book_req:false,
   seasonal:'Flooding Oct–Nov — some streets impassable',notes:'Inside the Ancient Town. Part of the combined ticket (5 sites). Small but informative. Combine with Assembly Halls.',alert:'OPEN DAILY · FLOOD RISK OCT–NOV'},
  {id:'ATT-C-008',region:'central',type:'museum',name:'Museum of Trade Ceramics (Hoi An)',dest:'Hoi An & Da Nang',
   hours:'Daily 08:00–17:00',closed:'None',admission:'Covered by Ancient Town ticket',duration:30,
   best_time:'Morning or afternoon',crowd:'Light',book_req:false,
   seasonal:'No closures',notes:'Covers 200 years of Hoi An\'s role in Asian ceramics trade. Small, well-presented. Good A/C.',alert:'OPEN DAILY'},
  {id:'ATT-C-009',region:'central',type:'museum',name:'Museum of Sa Huỳnh Culture (Hoi An)',dest:'Hoi An & Da Nang',
   hours:'Daily 08:00–17:00',closed:'None',admission:'Covered by Ancient Town ticket',duration:30,
   best_time:'Morning',crowd:'Very light',book_req:false,
   seasonal:'No closures',notes:'Pre-Cham culture artefacts. Very niche — good for archaeology-minded guests.',alert:'OPEN DAILY'},
  {id:'ATT-C-010',region:'central',type:'heritage',name:'Phong Nha Cave (Son Doong Region)',dest:'Phong Nha',
   hours:'Daily 07:30–16:00 (last entry 15:30)',closed:'None officially; check Oct–Nov floods',admission:'150,000 VND (Phong Nha) / varies',duration:120,
   best_time:'Morning, before tourist boats fill up',crowd:'Busy Feb–Aug; peaks Apr–May & Jul–Aug',book_req:true,
   seasonal:'CLOSED Oct–Nov some years due to flooding. Book 3+ weeks ahead in peak.',notes:'UNESCO. Boat tour inside cave. Combine with Paradise Cave (additional ticket). Book boatman in advance.',alert:'BOOK IN ADVANCE · CHECK OCT–NOV CLOSURES'},
  {id:'ATT-C-011',region:'central',type:'museum',name:'Quang Binh Museum (Phong Nha)',dest:'Phong Nha',
   hours:'Mon–Fri 07:30–11:30, 13:30–17:00',closed:'Weekend',admission:'Free',duration:30,
   best_time:'Weekday morning',crowd:'Very quiet',book_req:false,
   seasonal:'No closures',notes:'Covers wartime history of Quang Binh province. Small but contextually useful. Weekend closure is strict.',alert:'CLOSED WEEKENDS'},

  // ── SOUTH VIETNAM ──────────────────────────────────────────────
  {id:'ATT-S-001',region:'south',type:'museum',name:'War Remnants Museum (Ho Chi Minh City)',dest:'Ho Chi Minh City',
   hours:'Daily 07:30–18:00',closed:'None',admission:'40,000 VND',duration:90,
   best_time:'Morning (before emotional fatigue sets in)',crowd:'Very busy 08:30–12:00; calmer after 14:00',book_req:false,
   seasonal:'No seasonal closures',notes:'Emotionally intense. Allow 1.5 hours. Discuss with clients beforehand — not suitable for all guests. Photography allowed.',alert:'OPEN DAILY · EMOTIONALLY INTENSE — PREPARE CLIENTS'},
  {id:'ATT-S-002',region:'south',type:'museum',name:'Ho Chi Minh City Museum',dest:'Ho Chi Minh City',
   hours:'Daily 07:30–18:00',closed:'None',admission:'30,000 VND',duration:60,
   best_time:'Morning',crowd:'Moderate',book_req:false,
   seasonal:'No closures',notes:'Former Gia Long Palace. Covers colonial and revolutionary history. Hidden tunnels in basement. Well-maintained.',alert:'OPEN DAILY'},
  {id:'ATT-S-003',region:'south',type:'museum',name:'Museum of Vietnamese History (Saigon)',dest:'Ho Chi Minh City',
   hours:'Mon–Sat 08:00–17:00 (closed Tue lunch 11:00–13:30)',closed:'Tuesday lunch break',admission:'30,000 VND',duration:60,
   best_time:'Morning',crowd:'Light to moderate',book_req:false,
   seasonal:'No closures',notes:'Adjacent to Botanical Garden. Good chronological overview from prehistoric to 1975. Water puppetry shows on site.',alert:'TUE LUNCH CLOSED 11:00–13:30'},
  {id:'ATT-S-004',region:'south',type:'museum',name:'Independence Palace (Reunification Palace)',dest:'Ho Chi Minh City',
   hours:'Daily 07:30–11:00, 13:00–16:00',closed:'Public holidays may affect',admission:'40,000 VND',duration:75,
   best_time:'Morning session',crowd:'Busy on weekends; moderate weekdays',book_req:false,
   seasonal:'No closures',notes:'Former presidential palace. The original 1975 tank crash site is preserved. War room in basement fascinating.',alert:'OPEN DAILY · LUNCH BREAK 11:00–13:00'},
  {id:'ATT-S-005',region:'south',type:'museum',name:'Fine Arts Museum (Ho Chi Minh City)',dest:'Ho Chi Minh City',
   hours:'Tue–Sun 09:00–17:00',closed:'Monday',admission:'30,000 VND',duration:60,
   best_time:'Morning',crowd:'Very light — a hidden gem',book_req:false,
   seasonal:'No closures',notes:'Beautiful colonial building. Three floors of Vietnamese art from traditional to contemporary. Peaceful and underrated.',alert:'CLOSED MONDAYS'},
  {id:'ATT-S-006',region:'south',type:'heritage',name:'Cu Chi Tunnels (Ben Duoc or Ben Dinh)',dest:'Ho Chi Minh City',
   hours:'Daily 07:30–17:00',closed:'None',admission:'110,000 VND',duration:120,
   best_time:'Morning (cooler, less crowded)',crowd:'Very busy weekends; moderate weekdays',book_req:false,
   seasonal:'Hot and humid May–Sep; bring water',notes:'Ben Duoc (farther) is more authentic and less crowded than Ben Dinh. Wear comfortable clothes. Claustrophobic tunnels — warn guests.',alert:'OPEN DAILY · ARRIVE BEFORE 09:30 ON WEEKENDS'},
  {id:'ATT-S-007',region:'south',type:'museum',name:'Mekong Delta Eco Museum (Can Tho)',dest:'Can Tho',
   hours:'Daily 07:30–17:00',closed:'None',admission:'20,000 VND',duration:45,
   best_time:'Morning before floating market visits',crowd:'Very light',book_req:false,
   seasonal:'Flooding possible Sep–Nov',notes:'Covers Mekong river ecology and delta communities. Small but informative. Good orientation before river tours.',alert:'OPEN DAILY'},
  {id:'ATT-S-008',region:'south',type:'museum',name:'Can Tho Museum',dest:'Can Tho',
   hours:'Tue–Sun 08:00–11:30, 13:30–17:00',closed:'Monday',admission:'Free',duration:40,
   best_time:'Morning',crowd:'Very quiet',book_req:false,
   seasonal:'No closures',notes:'History of the Mekong Delta and Can Tho province. Combine with floating market visit (Cai Rang) for context.',alert:'CLOSED MONDAYS'},
  {id:'ATT-S-009',region:'south',type:'museum',name:'Da Lat Museum (Lam Dong Province Museum)',dest:'Da Lat',
   hours:'Mon–Fri 07:30–11:30, 13:30–17:00',closed:'Weekends',admission:'Free',duration:30,
   best_time:'Weekday morning',crowd:'Very quiet',book_req:false,
   seasonal:'No closures; cool year-round (1,500m altitude)',notes:'Covers highland ecology and ethnic minority culture. Useful background before trekking/village visits.',alert:'CLOSED WEEKENDS'},
  {id:'ATT-S-010',region:'south',type:'museum',name:'Khanh Hoa Museum (Nha Trang)',dest:'Nha Trang',
   hours:'Tue–Sun 08:00–11:30, 14:00–17:00',closed:'Monday',admission:'Free',duration:30,
   best_time:'Morning',crowd:'Very light',book_req:false,
   seasonal:'No seasonal closures',notes:'Overview of Cham culture and Khanh Hoa province history. Pair with Po Nagar Cham Towers visit nearby.',alert:'CLOSED MONDAYS'},
  {id:'ATT-S-011',region:'south',type:'heritage',name:'Po Nagar Cham Towers (Nha Trang)',dest:'Nha Trang',
   hours:'Daily 06:00–17:30',closed:'None',admission:'22,000 VND',duration:45,
   best_time:'Early morning (06:00–08:00) for best light and quiet',crowd:'Busy 09:00–12:00',book_req:false,
   seasonal:'Hot Apr–Aug; some festive ceremonies in spring',notes:'Active religious site — dress modestly, sarongs provided at entrance. Photography respectfully.',alert:'OPEN DAILY · DRESS CODE REQUIRED'},
  {id:'ATT-S-012',region:'south',type:'museum',name:'Con Dao Prison & Museum',dest:'Con Dao',
   hours:'Daily 07:30–11:30, 13:30–17:00',closed:'None',admission:'Free',duration:60,
   best_time:'Morning',crowd:'Very light (Con Dao is remote)',book_req:false,
   seasonal:'Accessible year-round by plane; sea rough Jun–Sep',notes:'Harrowing colonial-era prison complex. Very moving. Revolutionary cemetery also worth visiting. Context essential.',alert:'OPEN DAILY · EMOTIONALLY INTENSE'}
];

export type Attraction = (typeof ATTRACTION_DATA)[number];
