/* Auto-extracted from index.html — do not edit manually */

export const SEED_FEEDBACK = [
  {id:'FB-001',type:'client',date:'2026-04-18',bkid:'BK-T01',client:'Sarah Mitchell',nps:10,overall:'5',guide_r:'5',hotel_r:'5',best:'The private Halong Bay sunrise moment — absolutely magical. Nothing like this at home in New York.',improve:'',comments:'Minh was the best guide we have ever had anywhere in the world. We are already planning to come back.',again:'yes'},
  {id:'FB-002',type:'client',date:'2026-04-22',bkid:'BK-T02',client:'Jean-Pierre Moreau',nps:9,overall:'5',guide_r:'5',hotel_r:'4',best:'La Siesta Hoi An and the cooking class — exceeded expectations. Superb attention to detail.',improve:'Transfer from Da Nang airport could be more clearly communicated.',comments:'Très professionnel. We will definitely recommend The Ant Adventures to our friends in Paris.',again:'yes'},
  {id:'FB-003',type:'client',date:'2026-04-28',bkid:'BK-T03',client:'James Thornton',nps:8,overall:'4',guide_r:'4',hotel_r:'4',best:'Cycling through the rice paddies — pure Vietnam. Very authentic experience.',improve:'Day 3 itinerary felt slightly rushed. Would have loved more time at Hue Citadel.',comments:'Great overall. Minor timing issues but nothing that ruined the trip. Would recommend.',again:'yes'},
  {id:'FB-004',type:'client',date:'2026-05-02',bkid:'BK-T04',client:'Charu (ILV Group)',nps:10,overall:'5',guide_r:'5',hotel_r:'5',best:'Delta cycling route was perfectly curated for our group. Every detail was handled seamlessly.',improve:'',comments:'As a B2B agent sending clients regularly, this group has set the benchmark. Will be sending more bookings.',again:'yes'},
  {id:'FB-005',type:'client',date:'2026-05-06',bkid:'BK-T01',client:'Emma van der Berg',nps:7,overall:'4',guide_r:'4',hotel_r:'3',best:'Street food tour in Hanoi Old Quarter — unforgettable.',improve:'Hotel in Ninh Binh was slightly below expectations for the price point.',comments:'Good trip overall. Some elements were exceptional, others felt average for a luxury product.',again:'maybe'},
] as const;
