SET check_function_bodies = false;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;
CREATE SEQUENCE public.weather_fetch_log_id_seq;
CREATE SEQUENCE public.weather_forecast_cache_id_seq;
CREATE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;
GRANT ALL ON FUNCTION public.set_updated_at() TO anon;
GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;
CREATE TABLE public.accounts_payable (id text NOT NULL, booking_id text, supplier text NOT NULL, description text, amount numeric(12,2) DEFAULT 0, due_date date, status text DEFAULT 'Pending'::text, category text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.accounts_payable ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts_payable ADD CONSTRAINT accounts_payable_pkey PRIMARY KEY (id);
GRANT ALL ON public.accounts_payable TO anon;
GRANT ALL ON public.accounts_payable TO authenticated;
GRANT ALL ON public.accounts_payable TO service_role;
CREATE INDEX idx_ap_status ON public.accounts_payable (status);
CREATE INDEX idx_ap_due_date ON public.accounts_payable (due_date);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.accounts_payable FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.accounts_payable USING (true) WITH CHECK (true);
CREATE TABLE public.accounts_receivable (id text NOT NULL, finance_id text, booking_id text, cust_name text, tour text, invoice_amount numeric(12,2) DEFAULT 0, deposit_paid numeric(12,2) DEFAULT 0, balance numeric(12,2) GENERATED ALWAYS AS ((invoice_amount - deposit_paid)) STORED, due_date date, status text DEFAULT 'Outstanding'::text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.accounts_receivable ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts_receivable ADD CONSTRAINT accounts_receivable_pkey PRIMARY KEY (id);
GRANT ALL ON public.accounts_receivable TO anon;
GRANT ALL ON public.accounts_receivable TO authenticated;
GRANT ALL ON public.accounts_receivable TO service_role;
CREATE INDEX idx_ar_status ON public.accounts_receivable (status);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.accounts_receivable FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.accounts_receivable USING (true) WITH CHECK (true);
CREATE TABLE public.agents (id text NOT NULL, name text NOT NULL, country text, tier text, commission_pct numeric(5,2) DEFAULT 0, contact_name text, email text, phone text, currency text DEFAULT 'USD'::text, status text DEFAULT 'Active'::text, notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agents ADD CONSTRAINT agents_pkey PRIMARY KEY (id);
GRANT ALL ON public.agents TO anon;
GRANT ALL ON public.agents TO authenticated;
GRANT ALL ON public.agents TO service_role;
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.agents FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.agents USING (true) WITH CHECK (true);
CREATE TABLE public.attraction_photos (attraction_id text NOT NULL, photo_id text NOT NULL, sort_order smallint DEFAULT 0, is_featured boolean DEFAULT false NOT NULL);
ALTER TABLE public.attraction_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attraction_photos ADD CONSTRAINT attraction_photos_pkey PRIMARY KEY (attraction_id, photo_id);
GRANT ALL ON public.attraction_photos TO anon;
GRANT ALL ON public.attraction_photos TO authenticated;
GRANT ALL ON public.attraction_photos TO service_role;
CREATE INDEX idx_attraction_photos_photo ON public.attraction_photos (photo_id);
CREATE POLICY dev_allow_all ON public.attraction_photos USING (true) WITH CHECK (true);
CREATE TABLE public.attractions (id text NOT NULL, region text NOT NULL, type text NOT NULL, name text NOT NULL, dest text NOT NULL, hours text, closed text, admission text, duration smallint DEFAULT 0, best_time text, crowd text, book_req boolean DEFAULT false, seasonal text, notes text, alert text, phone text DEFAULT ''::text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.attractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attractions ADD CONSTRAINT attractions_pkey PRIMARY KEY (id);
ALTER TABLE public.attraction_photos ADD CONSTRAINT attraction_photos_attraction_id_fkey FOREIGN KEY (attraction_id) REFERENCES public.attractions(id) ON DELETE CASCADE;
ALTER TABLE public.attractions ADD CONSTRAINT attractions_region_check CHECK (region = ANY (ARRAY['north'::text, 'central'::text, 'south'::text]));
GRANT ALL ON public.attractions TO anon;
GRANT ALL ON public.attractions TO authenticated;
GRANT ALL ON public.attractions TO service_role;
CREATE INDEX idx_attractions_region ON public.attractions (region);
CREATE INDEX idx_attractions_type ON public.attractions (type);
CREATE INDEX idx_attractions_dest ON public.attractions (dest);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.attractions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.attractions USING (true) WITH CHECK (true);
CREATE TABLE public.booking_activities (id uuid DEFAULT gen_random_uuid() NOT NULL, itinerary_id uuid NOT NULL, name text NOT NULL, category text, sort_order smallint DEFAULT 0);
ALTER TABLE public.booking_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_activities ADD CONSTRAINT booking_activities_pkey PRIMARY KEY (id);
GRANT ALL ON public.booking_activities TO anon;
GRANT ALL ON public.booking_activities TO authenticated;
GRANT ALL ON public.booking_activities TO service_role;
CREATE POLICY dev_allow_all ON public.booking_activities USING (true) WITH CHECK (true);
CREATE TABLE public.booking_changes (id uuid DEFAULT gen_random_uuid() NOT NULL, booking_id text NOT NULL, changed_at timestamp with time zone DEFAULT now(), changed_by text, field_name text, old_value text, new_value text, note text);
ALTER TABLE public.booking_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_changes ADD CONSTRAINT booking_changes_pkey PRIMARY KEY (id);
GRANT ALL ON public.booking_changes TO anon;
GRANT ALL ON public.booking_changes TO authenticated;
GRANT ALL ON public.booking_changes TO service_role;
CREATE POLICY dev_allow_all ON public.booking_changes USING (true) WITH CHECK (true);
CREATE TABLE public.booking_itinerary (id uuid DEFAULT gen_random_uuid() NOT NULL, booking_id text NOT NULL, day_number smallint NOT NULL, destination text, hotel text, sort_order smallint DEFAULT 0);
ALTER TABLE public.booking_itinerary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_itinerary ADD CONSTRAINT booking_itinerary_pkey PRIMARY KEY (id);
ALTER TABLE public.booking_activities ADD CONSTRAINT booking_activities_itinerary_id_fkey FOREIGN KEY (itinerary_id) REFERENCES public.booking_itinerary(id) ON DELETE CASCADE;
ALTER TABLE public.booking_itinerary ADD CONSTRAINT uq_booking_day UNIQUE (booking_id, day_number);
GRANT ALL ON public.booking_itinerary TO anon;
GRANT ALL ON public.booking_itinerary TO authenticated;
GRANT ALL ON public.booking_itinerary TO service_role;
CREATE POLICY dev_allow_all ON public.booking_itinerary USING (true) WITH CHECK (true);
CREATE TABLE public.bookings (id text NOT NULL, cust_id text, lead_id text, tour text NOT NULL, pax smallint DEFAULT 1, start_date date, end_date date, total numeric(12,2) DEFAULT 0, deposit numeric(12,2) DEFAULT 0, status text DEFAULT 'Confirmed'::text, guide_id text, guide_name text, hotel text, guide_alert_pending boolean DEFAULT false, notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE public.accounts_payable ADD CONSTRAINT accounts_payable_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL;
ALTER TABLE public.accounts_receivable ADD CONSTRAINT accounts_receivable_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL;
ALTER TABLE public.booking_changes ADD CONSTRAINT booking_changes_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
ALTER TABLE public.booking_itinerary ADD CONSTRAINT booking_itinerary_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
GRANT ALL ON public.bookings TO anon;
GRANT ALL ON public.bookings TO authenticated;
GRANT ALL ON public.bookings TO service_role;
CREATE INDEX idx_bookings_start_date ON public.bookings (start_date);
CREATE INDEX idx_bookings_cust_id ON public.bookings (cust_id);
CREATE INDEX idx_bookings_guide_id ON public.bookings (guide_id);
CREATE INDEX idx_bookings_status ON public.bookings (status);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.bookings USING (true) WITH CHECK (true);
CREATE TABLE public.cal_events (id text NOT NULL, guide_id text, booking_id text, tour text, clients text, start_date date NOT NULL, end_date date NOT NULL, status text DEFAULT 'booked'::text, notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.cal_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cal_events ADD CONSTRAINT cal_events_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL;
ALTER TABLE public.cal_events ADD CONSTRAINT cal_events_pkey PRIMARY KEY (id);
GRANT ALL ON public.cal_events TO anon;
GRANT ALL ON public.cal_events TO authenticated;
GRANT ALL ON public.cal_events TO service_role;
CREATE INDEX idx_cal_events_dates ON public.cal_events (start_date, end_date);
CREATE INDEX idx_cal_events_guide ON public.cal_events (guide_id);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.cal_events FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.cal_events USING (true) WITH CHECK (true);
CREATE TABLE public.chat_channels (id text NOT NULL, display_name text NOT NULL, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.chat_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_channels ADD CONSTRAINT chat_channels_pkey PRIMARY KEY (id);
GRANT ALL ON public.chat_channels TO anon;
GRANT ALL ON public.chat_channels TO authenticated;
GRANT ALL ON public.chat_channels TO service_role;
CREATE POLICY dev_allow_all ON public.chat_channels USING (true) WITH CHECK (true);
CREATE TABLE public.chat_messages (id text NOT NULL, channel_id text NOT NULL, author text NOT NULL, body text NOT NULL, sent_at timestamp with time zone DEFAULT now());
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.chat_channels(id) ON DELETE CASCADE;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
GRANT ALL ON public.chat_messages TO anon;
GRANT ALL ON public.chat_messages TO authenticated;
GRANT ALL ON public.chat_messages TO service_role;
CREATE INDEX idx_chat_messages_channel ON public.chat_messages (channel_id);
CREATE INDEX idx_chat_messages_sent ON public.chat_messages (sent_at);
CREATE POLICY dev_allow_all ON public.chat_messages USING (true) WITH CHECK (true);
CREATE TABLE public.chat_reactions (message_id text NOT NULL, emoji text NOT NULL, added_by text DEFAULT ''::text NOT NULL);
ALTER TABLE public.chat_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_reactions ADD CONSTRAINT chat_reactions_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.chat_messages(id) ON DELETE CASCADE;
ALTER TABLE public.chat_reactions ADD CONSTRAINT chat_reactions_pkey PRIMARY KEY (message_id, emoji, added_by);
GRANT ALL ON public.chat_reactions TO anon;
GRANT ALL ON public.chat_reactions TO authenticated;
GRANT ALL ON public.chat_reactions TO service_role;
CREATE POLICY dev_allow_all ON public.chat_reactions USING (true) WITH CHECK (true);
CREATE TABLE public.comms (id text NOT NULL, cust_id text, comm_date date NOT NULL, type text, direction text DEFAULT 'outbound'::text, subject text, body text, author text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.comms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comms ADD CONSTRAINT comms_pkey PRIMARY KEY (id);
GRANT ALL ON public.comms TO anon;
GRANT ALL ON public.comms TO authenticated;
GRANT ALL ON public.comms TO service_role;
CREATE INDEX idx_comms_cust_id ON public.comms (cust_id);
CREATE INDEX idx_comms_date ON public.comms (comm_date);
CREATE POLICY dev_allow_all ON public.comms USING (true) WITH CHECK (true);
CREATE TABLE public.contracts (id text NOT NULL, booking_id text, client_name text NOT NULL, nationality text, pax smallint DEFAULT 1, rooms text, tour_name text NOT NULL, duration text, departure_date date, return_date date, route text, inclusions text, exclusions text, flights_info text, currency text DEFAULT 'USD'::text, total numeric(12,2) DEFAULT 0, deposit_pct smallint DEFAULT 30, deposit_amount numeric(12,2) DEFAULT 0, balance_due_date date, status text DEFAULT 'Draft'::text, created_at date, signed_at date, notes text, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contracts ADD CONSTRAINT contracts_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE RESTRICT;
ALTER TABLE public.contracts ADD CONSTRAINT contracts_pkey PRIMARY KEY (id);
GRANT ALL ON public.contracts TO anon;
GRANT ALL ON public.contracts TO authenticated;
GRANT ALL ON public.contracts TO service_role;
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.contracts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.contracts USING (true) WITH CHECK (true);
CREATE TABLE public.cruises (id text NOT NULL, supplier_id text, name text NOT NULL, route text, cabins text, rate text, valid_until text, rating text, notes text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.cruises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cruises ADD CONSTRAINT cruises_pkey PRIMARY KEY (id);
GRANT ALL ON public.cruises TO anon;
GRANT ALL ON public.cruises TO authenticated;
GRANT ALL ON public.cruises TO service_role;
CREATE POLICY dev_allow_all ON public.cruises USING (true) WITH CHECK (true);
CREATE TABLE public.customers (id text NOT NULL, name text NOT NULL, email text, phone text, whatsapp text, country text, nationality text, source text, travel_style text, language text, client_type text DEFAULT 'b2c'::text, agent_id text, salesperson text, hotel_tier text, budget text, travel_month text, children smallint DEFAULT 0, adults smallint DEFAULT 2, first_time text, intl_flights text, child_ages text, child_diet text, child_prefs text, flights text, visa_status text, interests text, donts text, notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ADD CONSTRAINT customers_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE SET NULL;
ALTER TABLE public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_cust_id_fkey FOREIGN KEY (cust_id) REFERENCES public.customers(id) ON DELETE RESTRICT;
ALTER TABLE public.comms ADD CONSTRAINT comms_cust_id_fkey FOREIGN KEY (cust_id) REFERENCES public.customers(id) ON DELETE CASCADE;
GRANT ALL ON public.customers TO anon;
GRANT ALL ON public.customers TO authenticated;
GRANT ALL ON public.customers TO service_role;
CREATE INDEX idx_customers_email ON public.customers (email);
CREATE INDEX idx_customers_agent_id ON public.customers (agent_id);
CREATE INDEX idx_customers_client_type ON public.customers (client_type);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.customers USING (true) WITH CHECK (true);
CREATE TABLE public.dev_notes (id text NOT NULL, title text NOT NULL, priority text DEFAULT 'medium'::text, category text, assignee text, status text DEFAULT 'open'::text, note_date date, author text, body text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.dev_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dev_notes ADD CONSTRAINT dev_notes_pkey PRIMARY KEY (id);
GRANT ALL ON public.dev_notes TO anon;
GRANT ALL ON public.dev_notes TO authenticated;
GRANT ALL ON public.dev_notes TO service_role;
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.dev_notes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.dev_notes USING (true) WITH CHECK (true);
CREATE TABLE public.feedback (id text NOT NULL, type text DEFAULT 'client'::text, feedback_date date, booking_id text, client_name text, nps smallint, overall_rating smallint, guide_rating smallint, hotel_rating smallint, best_moment text, improvement text, comments text, would_return text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ADD CONSTRAINT feedback_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL;
ALTER TABLE public.feedback ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);
GRANT ALL ON public.feedback TO anon;
GRANT ALL ON public.feedback TO authenticated;
GRANT ALL ON public.feedback TO service_role;
CREATE INDEX idx_feedback_booking ON public.feedback (booking_id);
CREATE POLICY dev_allow_all ON public.feedback USING (true) WITH CHECK (true);
CREATE TABLE public.finance (id text NOT NULL, booking_id text, cust_name text, type text NOT NULL, txn_date date, month text, revenue numeric(12,2) DEFAULT 0, cost numeric(12,2) DEFAULT 0, cash_in numeric(12,2) DEFAULT 0, cash_out numeric(12,2) DEFAULT 0, status text DEFAULT 'Pending'::text, invoice_ref text, notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.finance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance ADD CONSTRAINT finance_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL;
ALTER TABLE public.finance ADD CONSTRAINT finance_pkey PRIMARY KEY (id);
ALTER TABLE public.accounts_receivable ADD CONSTRAINT accounts_receivable_finance_id_fkey FOREIGN KEY (finance_id) REFERENCES public.finance(id) ON DELETE SET NULL;
GRANT ALL ON public.finance TO anon;
GRANT ALL ON public.finance TO authenticated;
GRANT ALL ON public.finance TO service_role;
CREATE INDEX idx_finance_type ON public.finance (type);
CREATE INDEX idx_finance_booking_id ON public.finance (booking_id);
CREATE INDEX idx_finance_month ON public.finance (month);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.finance FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.finance USING (true) WITH CHECK (true);
CREATE TABLE public.guide_reviews (id uuid DEFAULT gen_random_uuid() NOT NULL, guide_id text NOT NULL, booking_id text, reviewer_name text, rating smallint, comment text, review_date date);
ALTER TABLE public.guide_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guide_reviews ADD CONSTRAINT fk_guide_reviews_booking FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL;
ALTER TABLE public.guide_reviews ADD CONSTRAINT guide_reviews_pkey PRIMARY KEY (id);
GRANT ALL ON public.guide_reviews TO anon;
GRANT ALL ON public.guide_reviews TO authenticated;
GRANT ALL ON public.guide_reviews TO service_role;
CREATE POLICY dev_allow_all ON public.guide_reviews USING (true) WITH CHECK (true);
CREATE TABLE public.guides (id text NOT NULL, full_name text NOT NULL, english_name text, region text, languages text, specialty text, license_number text, daily_rate numeric(10,2) DEFAULT 0, rating text, status text DEFAULT 'Active'::text, photo_url text, years_exp smallint DEFAULT 0, location text, phone text, email text, shirt_size text, bank_account text, address text, bio text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.guides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guides ADD CONSTRAINT guides_pkey PRIMARY KEY (id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_guide_id_fkey FOREIGN KEY (guide_id) REFERENCES public.guides(id) ON DELETE SET NULL;
ALTER TABLE public.cal_events ADD CONSTRAINT cal_events_guide_id_fkey FOREIGN KEY (guide_id) REFERENCES public.guides(id) ON DELETE CASCADE;
ALTER TABLE public.guide_reviews ADD CONSTRAINT guide_reviews_guide_id_fkey FOREIGN KEY (guide_id) REFERENCES public.guides(id) ON DELETE CASCADE;
GRANT ALL ON public.guides TO anon;
GRANT ALL ON public.guides TO authenticated;
GRANT ALL ON public.guides TO service_role;
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.guides FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.guides USING (true) WITH CHECK (true);
CREATE TABLE public.hotel_rooms (id text NOT NULL, hotel_id text NOT NULL, room_type text NOT NULL, view text, sqm smallint, low_mup numeric, high_mup numeric, festive_mup numeric, peak_mup numeric, low_net numeric, high_net numeric, festive_net numeric, peak_net numeric, sort_order smallint DEFAULT 0, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.hotel_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hotel_rooms ADD CONSTRAINT hotel_rooms_pkey PRIMARY KEY (id);
GRANT ALL ON public.hotel_rooms TO anon;
GRANT ALL ON public.hotel_rooms TO authenticated;
GRANT ALL ON public.hotel_rooms TO service_role;
CREATE TABLE public.hotels (id text NOT NULL, name text NOT NULL, destination text NOT NULL, category text, stars text, region text NOT NULL, status text DEFAULT 'Active'::text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hotels ADD CONSTRAINT hotels_pkey PRIMARY KEY (id);
ALTER TABLE public.hotel_rooms ADD CONSTRAINT hotel_rooms_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.hotels(id) ON DELETE CASCADE;
GRANT ALL ON public.hotels TO anon;
GRANT ALL ON public.hotels TO authenticated;
GRANT ALL ON public.hotels TO service_role;
CREATE TABLE public.leads (id text NOT NULL, cust_id text, tour text, pax smallint DEFAULT 1, value numeric(12,2) DEFAULT 0, currency text DEFAULT 'USD'::text, month text, stage text DEFAULT 'Inquiry'::text, owner text, follow_up_date date, next_action text, probability smallint DEFAULT 0, client_type text, notes text, needs_tour_design boolean DEFAULT false, tour_design_acked boolean DEFAULT false, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ADD CONSTRAINT chk_leads_stage CHECK (stage = ANY (ARRAY['Inquiry'::text, 'Designing'::text, 'Quoted'::text, 'Negotiation'::text, 'Confirmed'::text, 'On Tour'::text, 'Completed'::text, 'Lost'::text, 'Pending'::text]));
ALTER TABLE public.leads ADD CONSTRAINT leads_cust_id_fkey FOREIGN KEY (cust_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.leads ADD CONSTRAINT leads_pkey PRIMARY KEY (id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE SET NULL;
GRANT ALL ON public.leads TO anon;
GRANT ALL ON public.leads TO authenticated;
GRANT ALL ON public.leads TO service_role;
CREATE INDEX idx_leads_owner ON public.leads (owner);
CREATE INDEX idx_leads_stage ON public.leads (stage);
CREATE INDEX idx_leads_needs_tour_design ON public.leads (needs_tour_design) WHERE needs_tour_design = true;
CREATE INDEX idx_leads_cust_id ON public.leads (cust_id);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.leads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.leads USING (true) WITH CHECK (true);
CREATE TABLE public.photo_tags (photo_id text NOT NULL, tag text NOT NULL);
ALTER TABLE public.photo_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photo_tags ADD CONSTRAINT photo_tags_pkey PRIMARY KEY (photo_id, tag);
GRANT ALL ON public.photo_tags TO anon;
GRANT ALL ON public.photo_tags TO authenticated;
GRANT ALL ON public.photo_tags TO service_role;
CREATE POLICY dev_allow_all ON public.photo_tags USING (true) WITH CHECK (true);
CREATE TABLE public.photos (id text NOT NULL, caption text, region text, url text, thumb_url text, storage_path text, display_bytes integer, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos ADD CONSTRAINT photos_pkey PRIMARY KEY (id);
ALTER TABLE public.attraction_photos ADD CONSTRAINT attraction_photos_photo_id_fkey FOREIGN KEY (photo_id) REFERENCES public.photos(id) ON DELETE CASCADE;
ALTER TABLE public.photo_tags ADD CONSTRAINT photo_tags_photo_id_fkey FOREIGN KEY (photo_id) REFERENCES public.photos(id) ON DELETE CASCADE;
GRANT ALL ON public.photos TO anon;
GRANT ALL ON public.photos TO authenticated;
GRANT ALL ON public.photos TO service_role;
CREATE POLICY dev_allow_all ON public.photos USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_acc_cruise_rates (id text NOT NULL, sheet text DEFAULT ''::text NOT NULL, region text DEFAULT ''::text, location text DEFAULT ''::text, property_name text NOT NULL, stars text DEFAULT ''::text, type text DEFAULT 'Cruise'::text, room_type text DEFAULT ''::text, phone text DEFAULT ''::text, email text DEFAULT ''::text, cost_2026 numeric, cost_2027 numeric, sell_2026 numeric, sell_2027 numeric, markup_pct numeric, margin numeric, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_acc_cruise_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_acc_cruise_rates ADD CONSTRAINT pricing_acc_cruise_rates_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_acc_cruise_rates TO anon;
GRANT ALL ON public.pricing_acc_cruise_rates TO authenticated;
GRANT ALL ON public.pricing_acc_cruise_rates TO service_role;
CREATE INDEX idx_pricing_acc_cruise_sheet ON public.pricing_acc_cruise_rates (sheet);
CREATE POLICY dev_allow_all ON public.pricing_acc_cruise_rates USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_acc_properties (id text NOT NULL, region text DEFAULT ''::text, location text DEFAULT ''::text, name text NOT NULL, website text DEFAULT ''::text, address text DEFAULT ''::text, ownership text DEFAULT ''::text, stars text DEFAULT ''::text, type text DEFAULT ''::text, reservations_contact text DEFAULT ''::text, sales_contact text DEFAULT ''::text, factsheet_link text DEFAULT ''::text, contract_renewal text DEFAULT ''::text, bank_account text DEFAULT ''::text, approved text DEFAULT ''::text, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_acc_properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_acc_properties ADD CONSTRAINT pricing_acc_properties_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_acc_properties TO anon;
GRANT ALL ON public.pricing_acc_properties TO authenticated;
GRANT ALL ON public.pricing_acc_properties TO service_role;
CREATE INDEX idx_pricing_acc_props_type ON public.pricing_acc_properties (type);
CREATE INDEX idx_pricing_acc_props_region ON public.pricing_acc_properties (region);
CREATE POLICY dev_allow_all ON public.pricing_acc_properties USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_acc_room_rates (id text NOT NULL, sheet text DEFAULT ''::text NOT NULL, location text DEFAULT ''::text, property_name text NOT NULL, room_type text NOT NULL, season text DEFAULT ''::text, period_from text DEFAULT ''::text, period_to text DEFAULT ''::text, year_label text DEFAULT ''::text, vnd_cost numeric, usd_cost numeric, sell_price numeric, margin numeric, notes text DEFAULT ''::text, sort_order integer DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_acc_room_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_acc_room_rates ADD CONSTRAINT pricing_acc_room_rates_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_acc_room_rates TO anon;
GRANT ALL ON public.pricing_acc_room_rates TO authenticated;
GRANT ALL ON public.pricing_acc_room_rates TO service_role;
CREATE INDEX idx_pricing_acc_rates_sheet ON public.pricing_acc_room_rates (sheet);
CREATE INDEX idx_pricing_acc_rates_property ON public.pricing_acc_room_rates (property_name);
CREATE POLICY dev_allow_all ON public.pricing_acc_room_rates USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_catalog_imports (id text NOT NULL, workbook text NOT NULL, file_name text NOT NULL, sheet_count smallint DEFAULT 0, row_count integer DEFAULT 0, warning_count smallint DEFAULT 0, imported_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_catalog_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_catalog_imports ADD CONSTRAINT pricing_catalog_imports_pkey PRIMARY KEY (id);
ALTER TABLE public.pricing_catalog_imports ADD CONSTRAINT pricing_catalog_imports_workbook_check CHECK (workbook = ANY (ARRAY['essentials'::text, 'accommodation'::text]));
GRANT ALL ON public.pricing_catalog_imports TO anon;
GRANT ALL ON public.pricing_catalog_imports TO authenticated;
GRANT ALL ON public.pricing_catalog_imports TO service_role;
CREATE INDEX idx_pricing_imports_workbook ON public.pricing_catalog_imports (workbook, imported_at DESC);
CREATE POLICY dev_allow_all ON public.pricing_catalog_imports USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_ess_car_rates (id text NOT NULL, category text DEFAULT ''::text, tour_title text DEFAULT ''::text, route text DEFAULT ''::text, km numeric, duration text DEFAULT ''::text, s7 numeric, s16 numeric, s29 numeric, s35 numeric, s45 numeric, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_ess_car_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_ess_car_rates ADD CONSTRAINT pricing_ess_car_rates_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_ess_car_rates TO anon;
GRANT ALL ON public.pricing_ess_car_rates TO authenticated;
GRANT ALL ON public.pricing_ess_car_rates TO service_role;
CREATE POLICY dev_allow_all ON public.pricing_ess_car_rates USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_ess_cost_lines (id text NOT NULL, product_code text NOT NULL, group_label text DEFAULT ''::text, label text NOT NULL, kind text DEFAULT 'component'::text NOT NULL, p1 numeric, p2 numeric, p3 numeric, p4 numeric, p5 numeric, p6 numeric, p7 numeric, p8 numeric, p9 numeric, p10 numeric, p11 numeric, p12 numeric, p13 numeric, p14 numeric, p15 numeric, p16 numeric, p17 numeric, p18 numeric, p19 numeric, p20 numeric, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_ess_cost_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_ess_cost_lines ADD CONSTRAINT pricing_ess_cost_lines_kind_check CHECK (kind = ANY (ARRAY['component'::text, 'hotel'::text, 'selling_group'::text, 'selling_pax'::text, 'surcharge'::text]));
ALTER TABLE public.pricing_ess_cost_lines ADD CONSTRAINT pricing_ess_cost_lines_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_ess_cost_lines TO anon;
GRANT ALL ON public.pricing_ess_cost_lines TO authenticated;
GRANT ALL ON public.pricing_ess_cost_lines TO service_role;
CREATE INDEX idx_pricing_cost_lines_product ON public.pricing_ess_cost_lines (product_code);
CREATE POLICY dev_allow_all ON public.pricing_ess_cost_lines USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_ess_hotel_rates (id text NOT NULL, sheet text DEFAULT ''::text NOT NULL, property text DEFAULT ''::text, section text DEFAULT ''::text, room_type text NOT NULL, variant_a text DEFAULT ''::text, variant_b text DEFAULT ''::text, vnd_a numeric, vnd_b numeric, usd_a numeric, usd_b numeric, sell_a numeric, sell_b numeric, notes text DEFAULT ''::text, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_ess_hotel_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_ess_hotel_rates ADD CONSTRAINT pricing_ess_hotel_rates_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_ess_hotel_rates TO anon;
GRANT ALL ON public.pricing_ess_hotel_rates TO authenticated;
GRANT ALL ON public.pricing_ess_hotel_rates TO service_role;
CREATE INDEX idx_pricing_hotel_rates_sheet ON public.pricing_ess_hotel_rates (sheet);
CREATE POLICY dev_allow_all ON public.pricing_ess_hotel_rates USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_ess_notes (id text NOT NULL, sheet text DEFAULT ''::text NOT NULL, section text DEFAULT ''::text, label text DEFAULT ''::text, detail text DEFAULT ''::text, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_ess_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_ess_notes ADD CONSTRAINT pricing_ess_notes_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_ess_notes TO anon;
GRANT ALL ON public.pricing_ess_notes TO authenticated;
GRANT ALL ON public.pricing_ess_notes TO service_role;
CREATE INDEX idx_pricing_notes_sheet ON public.pricing_ess_notes (sheet);
CREATE POLICY dev_allow_all ON public.pricing_ess_notes USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_ess_products (code text NOT NULL, seq smallint DEFAULT 0, category text DEFAULT ''::text, name text NOT NULL, duration_days numeric, overnight text DEFAULT ''::text, journeys text DEFAULT ''::text, incl_7s text DEFAULT ''::text, incl_16s text DEFAULT ''::text, incl_29s text DEFAULT ''::text, incl_35s text DEFAULT ''::text, guide_main numeric, guide_assistant numeric, guide_overnight numeric, truck_price numeric, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_ess_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_ess_products ADD CONSTRAINT pricing_ess_products_pkey PRIMARY KEY (code);
ALTER TABLE public.pricing_ess_cost_lines ADD CONSTRAINT pricing_ess_cost_lines_product_code_fkey FOREIGN KEY (product_code) REFERENCES public.pricing_ess_products(code) ON DELETE CASCADE;
GRANT ALL ON public.pricing_ess_products TO anon;
GRANT ALL ON public.pricing_ess_products TO authenticated;
GRANT ALL ON public.pricing_ess_products TO service_role;
CREATE POLICY dev_allow_all ON public.pricing_ess_products USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_ess_services (id text NOT NULL, block text DEFAULT ''::text, label text NOT NULL, unit text DEFAULT ''::text, amount numeric, amount2 numeric, notes text DEFAULT ''::text, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_ess_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_ess_services ADD CONSTRAINT pricing_ess_services_pkey PRIMARY KEY (id);
GRANT ALL ON public.pricing_ess_services TO anon;
GRANT ALL ON public.pricing_ess_services TO authenticated;
GRANT ALL ON public.pricing_ess_services TO service_role;
CREATE POLICY dev_allow_all ON public.pricing_ess_services USING (true) WITH CHECK (true);
CREATE TABLE public.pricing_settings (id text NOT NULL, workbook text NOT NULL, sheet text DEFAULT ''::text NOT NULL, key text NOT NULL, label text DEFAULT ''::text NOT NULL, value_num numeric, value_text text DEFAULT ''::text, sort_order smallint DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pricing_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_settings ADD CONSTRAINT pricing_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.pricing_settings ADD CONSTRAINT pricing_settings_workbook_check CHECK (workbook = ANY (ARRAY['essentials'::text, 'accommodation'::text]));
GRANT ALL ON public.pricing_settings TO anon;
GRANT ALL ON public.pricing_settings TO authenticated;
GRANT ALL ON public.pricing_settings TO service_role;
CREATE INDEX idx_pricing_settings_workbook ON public.pricing_settings (workbook);
CREATE POLICY dev_allow_all ON public.pricing_settings USING (true) WITH CHECK (true);
CREATE TABLE public.product_photos (product_code text NOT NULL, photo_id text NOT NULL, sort_order smallint DEFAULT 0, is_featured boolean DEFAULT false NOT NULL);
ALTER TABLE public.product_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_photos ADD CONSTRAINT product_photos_photo_id_fkey FOREIGN KEY (photo_id) REFERENCES public.photos(id) ON DELETE CASCADE;
ALTER TABLE public.product_photos ADD CONSTRAINT product_photos_pkey PRIMARY KEY (product_code, photo_id);
GRANT ALL ON public.product_photos TO anon;
GRANT ALL ON public.product_photos TO authenticated;
GRANT ALL ON public.product_photos TO service_role;
CREATE INDEX idx_product_photos_photo ON public.product_photos (photo_id);
CREATE POLICY dev_allow_all ON public.product_photos USING (true) WITH CHECK (true);
CREATE TABLE public.product_pricing (product_code text NOT NULL, std_cost numeric DEFAULT 0, p1 numeric DEFAULT 0, p2 numeric DEFAULT 0, p3 numeric DEFAULT 0, p4 numeric DEFAULT 0, p5 numeric DEFAULT 0, p6 numeric DEFAULT 0, p7 numeric DEFAULT 0, p8 numeric DEFAULT 0, p9 numeric DEFAULT 0, p10 numeric DEFAULT 0, c1 numeric DEFAULT 0, c2 numeric DEFAULT 0, c3 numeric DEFAULT 0, c4 numeric DEFAULT 0, c5 numeric DEFAULT 0, c6 numeric DEFAULT 0, c7 numeric DEFAULT 0, c8 numeric DEFAULT 0, c9 numeric DEFAULT 0, c10 numeric DEFAULT 0, incl_guide boolean DEFAULT false, incl_transport boolean DEFAULT false, incl_tickets boolean DEFAULT false, incl_water boolean DEFAULT false, incl_meals boolean DEFAULT false, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.product_pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_pricing ADD CONSTRAINT product_pricing_pkey PRIMARY KEY (product_code);
GRANT ALL ON public.product_pricing TO anon;
GRANT ALL ON public.product_pricing TO authenticated;
GRANT ALL ON public.product_pricing TO service_role;
CREATE POLICY dev_allow_all ON public.product_pricing USING (true) WITH CHECK (true);
CREATE TABLE public.products (code text NOT NULL, name text NOT NULL, logic text, duration text, category text, destination text, level text, description text, usp text, notes_to_sales text, price_from text, region text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (code);
ALTER TABLE public.product_photos ADD CONSTRAINT product_photos_product_code_fkey FOREIGN KEY (product_code) REFERENCES public.products(code) ON DELETE CASCADE;
ALTER TABLE public.product_pricing ADD CONSTRAINT product_pricing_product_code_fkey FOREIGN KEY (product_code) REFERENCES public.products(code) ON DELETE CASCADE;
GRANT ALL ON public.products TO anon;
GRANT ALL ON public.products TO authenticated;
GRANT ALL ON public.products TO service_role;
CREATE INDEX idx_products_region ON public.products (region);
CREATE INDEX idx_products_category ON public.products (category);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.products USING (true) WITH CHECK (true);
CREATE TABLE public.restaurants (id text NOT NULL, supplier_id text, name text NOT NULL, city text, cuisine text, set_menu text, capacity smallint, rating text, notes text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);
GRANT ALL ON public.restaurants TO anon;
GRANT ALL ON public.restaurants TO authenticated;
GRANT ALL ON public.restaurants TO service_role;
CREATE POLICY dev_allow_all ON public.restaurants USING (true) WITH CHECK (true);
CREATE TABLE public.salary_records (id uuid DEFAULT gen_random_uuid() NOT NULL, staff_id text NOT NULL, month text NOT NULL, base numeric(10,2) DEFAULT 0, bonus numeric(10,2) DEFAULT 0, deductions numeric(10,2) DEFAULT 0, net_pay numeric(10,2) GENERATED ALWAYS AS (((base + bonus) - deductions)) STORED, paid_date date, status text DEFAULT 'Pending'::text, notes text);
ALTER TABLE public.salary_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salary_records ADD CONSTRAINT salary_records_pkey PRIMARY KEY (id);
GRANT ALL ON public.salary_records TO anon;
GRANT ALL ON public.salary_records TO authenticated;
GRANT ALL ON public.salary_records TO service_role;
CREATE POLICY dev_allow_all ON public.salary_records USING (true) WITH CHECK (true);
CREATE TABLE public.staff (id text NOT NULL, name text NOT NULL, english_name text, department text, "position" text, phone text, email text, start_date date, contract_type text DEFAULT 'Full-time'::text, base_salary numeric(10,2) DEFAULT 0, status text DEFAULT 'Active'::text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ADD CONSTRAINT staff_pkey PRIMARY KEY (id);
ALTER TABLE public.salary_records ADD CONSTRAINT salary_records_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id) ON DELETE CASCADE;
GRANT ALL ON public.staff TO anon;
GRANT ALL ON public.staff TO authenticated;
GRANT ALL ON public.staff TO service_role;
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.staff FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.staff USING (true) WITH CHECK (true);
CREATE TABLE public.supplier_tags (supplier_id text NOT NULL, tag text NOT NULL);
ALTER TABLE public.supplier_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_tags ADD CONSTRAINT supplier_tags_pkey PRIMARY KEY (supplier_id, tag);
GRANT ALL ON public.supplier_tags TO anon;
GRANT ALL ON public.supplier_tags TO authenticated;
GRANT ALL ON public.supplier_tags TO service_role;
CREATE POLICY dev_allow_all ON public.supplier_tags USING (true) WITH CHECK (true);
CREATE TABLE public.suppliers (id text NOT NULL, category text NOT NULL, subcategory text, name text NOT NULL, english_name text, contact_name text, phone text, email text, location text, region text, rate text, currency text DEFAULT 'USD'::text, payment_terms text, has_contract boolean DEFAULT false, cancellation_policy text, insurance_info text, availability text, description text, notes text, rating text, status text DEFAULT 'Active'::text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);
ALTER TABLE public.cruises ADD CONSTRAINT cruises_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.supplier_tags ADD CONSTRAINT supplier_tags_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE CASCADE;
GRANT ALL ON public.suppliers TO anon;
GRANT ALL ON public.suppliers TO authenticated;
GRANT ALL ON public.suppliers TO service_role;
CREATE INDEX idx_suppliers_status ON public.suppliers (status);
CREATE INDEX idx_suppliers_category ON public.suppliers (category);
CREATE INDEX idx_suppliers_region ON public.suppliers (region);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.suppliers USING (true) WITH CHECK (true);
CREATE TABLE public.tasks (id text NOT NULL, title text NOT NULL, assignee text, due_date date, priority text DEFAULT 'medium'::text, department text, status text DEFAULT 'todo'::text, booking_id text, notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);
GRANT ALL ON public.tasks TO anon;
GRANT ALL ON public.tasks TO authenticated;
GRANT ALL ON public.tasks TO service_role;
CREATE INDEX idx_tasks_assignee ON public.tasks (assignee);
CREATE INDEX idx_tasks_due_date ON public.tasks (due_date);
CREATE INDEX idx_tasks_status ON public.tasks (status);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.tasks USING (true) WITH CHECK (true);
CREATE TABLE public.tax_reports (id text NOT NULL, period text NOT NULL, revenue numeric(14,2) DEFAULT 0, expenses numeric(14,2) DEFAULT 0, vat_output numeric(12,2) DEFAULT 0, vat_input numeric(12,2) DEFAULT 0, vat_payable numeric(12,2) GENERATED ALWAYS AS ((vat_output - vat_input)) STORED, profit_before_tax numeric(14,2) GENERATED ALWAYS AS ((revenue - expenses)) STORED, corp_tax numeric(12,2) DEFAULT 0, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.tax_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_reports ADD CONSTRAINT tax_reports_pkey PRIMARY KEY (id);
GRANT ALL ON public.tax_reports TO anon;
GRANT ALL ON public.tax_reports TO authenticated;
GRANT ALL ON public.tax_reports TO service_role;
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.tax_reports FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.tax_reports USING (true) WITH CHECK (true);
CREATE TABLE public.tour_drafts (id text NOT NULL, lead_id text, cust_id text, brief_json jsonb, outline_status text DEFAULT 'draft'::text, outline_notes text, outline_sent_at timestamp with time zone, outline_approved_at timestamp with time zone, outline_revision smallint DEFAULT 0, selected_codes text[], selected_package_id text, markup_pct numeric(5,2) DEFAULT 30, client_type text DEFAULT 'b2c'::text, current_step smallint DEFAULT 0, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.tour_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tour_drafts ADD CONSTRAINT chk_outline_status CHECK (outline_status = ANY (ARRAY['draft'::text, 'sent'::text, 'approved'::text]));
ALTER TABLE public.tour_drafts ADD CONSTRAINT tour_drafts_cust_id_fkey FOREIGN KEY (cust_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.tour_drafts ADD CONSTRAINT tour_drafts_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE;
ALTER TABLE public.tour_drafts ADD CONSTRAINT tour_drafts_lead_id_key UNIQUE (lead_id);
ALTER TABLE public.tour_drafts ADD CONSTRAINT tour_drafts_pkey PRIMARY KEY (id);
GRANT ALL ON public.tour_drafts TO anon;
GRANT ALL ON public.tour_drafts TO authenticated;
GRANT ALL ON public.tour_drafts TO service_role;
CREATE INDEX idx_tour_drafts_cust_id ON public.tour_drafts (cust_id);
CREATE INDEX idx_tour_drafts_lead_id ON public.tour_drafts (lead_id);
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.tour_drafts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.tour_drafts USING (true) WITH CHECK (true);
CREATE TABLE public.tour_outline_days (id uuid DEFAULT gen_random_uuid() NOT NULL, draft_id text NOT NULL, day_number smallint NOT NULL, outline_date date, location text, activities text, hotels text, sort_order smallint DEFAULT 0);
ALTER TABLE public.tour_outline_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tour_outline_days ADD CONSTRAINT tour_outline_days_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.tour_drafts(id) ON DELETE CASCADE;
ALTER TABLE public.tour_outline_days ADD CONSTRAINT tour_outline_days_pkey PRIMARY KEY (id);
ALTER TABLE public.tour_outline_days ADD CONSTRAINT uq_tour_outline_day UNIQUE (draft_id, day_number);
GRANT ALL ON public.tour_outline_days TO anon;
GRANT ALL ON public.tour_outline_days TO authenticated;
GRANT ALL ON public.tour_outline_days TO service_role;
CREATE INDEX idx_tour_outline_days_draft ON public.tour_outline_days (draft_id);
CREATE POLICY dev_allow_all ON public.tour_outline_days USING (true) WITH CHECK (true);
CREATE TABLE public.transport (id text NOT NULL, supplier_id text, name text NOT NULL, region text, vehicles text, rate text, notes text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.transport ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transport ADD CONSTRAINT transport_pkey PRIMARY KEY (id);
ALTER TABLE public.transport ADD CONSTRAINT transport_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
GRANT ALL ON public.transport TO anon;
GRANT ALL ON public.transport TO authenticated;
GRANT ALL ON public.transport TO service_role;
CREATE POLICY dev_allow_all ON public.transport USING (true) WITH CHECK (true);
CREATE TABLE public.weather_destinations (id text NOT NULL, name text NOT NULL, region text NOT NULL, emoji text, latitude numeric(9,6) NOT NULL, longitude numeric(9,6) NOT NULL, elevation_m integer, sort_order integer DEFAULT 0, active boolean DEFAULT true, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.weather_destinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weather_destinations ADD CONSTRAINT weather_destinations_pkey PRIMARY KEY (id);
ALTER TABLE public.weather_destinations ADD CONSTRAINT weather_destinations_region_check CHECK (region = ANY (ARRAY['north'::text, 'central'::text, 'south'::text]));
GRANT ALL ON public.weather_destinations TO anon;
GRANT ALL ON public.weather_destinations TO authenticated;
GRANT ALL ON public.weather_destinations TO service_role;
CREATE TRIGGER trg_updated_at BEFORE UPDATE ON public.weather_destinations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY dev_allow_all ON public.weather_destinations USING (true) WITH CHECK (true);
CREATE TABLE public.weather_fetch_log (id bigint DEFAULT nextval('public.weather_fetch_log_id_seq'::regclass) NOT NULL, fetched_at timestamp with time zone DEFAULT now(), status text NOT NULL, destinations_count integer DEFAULT 0, duration_ms integer, error_message text);
ALTER SEQUENCE public.weather_fetch_log_id_seq OWNED BY public.weather_fetch_log.id;
GRANT ALL ON SEQUENCE public.weather_fetch_log_id_seq TO anon;
GRANT ALL ON SEQUENCE public.weather_fetch_log_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.weather_fetch_log_id_seq TO service_role;
ALTER TABLE public.weather_fetch_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weather_fetch_log ADD CONSTRAINT weather_fetch_log_pkey PRIMARY KEY (id);
ALTER TABLE public.weather_fetch_log ADD CONSTRAINT weather_fetch_log_status_check CHECK (status = ANY (ARRAY['ok'::text, 'error'::text, 'skipped'::text]));
GRANT ALL ON public.weather_fetch_log TO anon;
GRANT ALL ON public.weather_fetch_log TO authenticated;
GRANT ALL ON public.weather_fetch_log TO service_role;
CREATE INDEX idx_weather_fetch_log_at ON public.weather_fetch_log (fetched_at DESC);
CREATE POLICY dev_allow_all ON public.weather_fetch_log USING (true) WITH CHECK (true);
CREATE TABLE public.weather_forecast_cache (id bigint DEFAULT nextval('public.weather_forecast_cache_id_seq'::regclass) NOT NULL, destination_id text NOT NULL, forecast_date date NOT NULL, temp_min_c numeric(5,1) NOT NULL, temp_max_c numeric(5,1) NOT NULL, precip_mm numeric(6,1) DEFAULT 0, wind_kmh numeric(6,1), weather_code integer NOT NULL, travel_rating text NOT NULL, fetched_at timestamp with time zone NOT NULL, expires_at timestamp with time zone NOT NULL);
ALTER SEQUENCE public.weather_forecast_cache_id_seq OWNED BY public.weather_forecast_cache.id;
GRANT ALL ON SEQUENCE public.weather_forecast_cache_id_seq TO anon;
GRANT ALL ON SEQUENCE public.weather_forecast_cache_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.weather_forecast_cache_id_seq TO service_role;
ALTER TABLE public.weather_forecast_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weather_forecast_cache ADD CONSTRAINT weather_forecast_cache_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.weather_destinations(id) ON DELETE CASCADE;
ALTER TABLE public.weather_forecast_cache ADD CONSTRAINT weather_forecast_cache_destination_id_forecast_date_key UNIQUE (destination_id, forecast_date);
ALTER TABLE public.weather_forecast_cache ADD CONSTRAINT weather_forecast_cache_pkey PRIMARY KEY (id);
ALTER TABLE public.weather_forecast_cache ADD CONSTRAINT weather_forecast_cache_travel_rating_check CHECK (travel_rating = ANY (ARRAY['E'::text, 'G'::text, 'F'::text, 'P'::text]));
GRANT ALL ON public.weather_forecast_cache TO anon;
GRANT ALL ON public.weather_forecast_cache TO authenticated;
GRANT ALL ON public.weather_forecast_cache TO service_role;
CREATE INDEX idx_weather_cache_date ON public.weather_forecast_cache (forecast_date);
CREATE INDEX idx_weather_cache_dest ON public.weather_forecast_cache (destination_id);
CREATE INDEX idx_weather_cache_expires ON public.weather_forecast_cache (expires_at);
CREATE POLICY dev_allow_all ON public.weather_forecast_cache USING (true) WITH CHECK (true);
