-- CRM unified lookup catalogs + Settings permissions
-- Seeded from former client-side constants (countries, nationalities, sources, …).

create table if not exists public.crm_catalog_items (
  kind text not null check (kind ~ '^[a-z][a-z0-9_]{0,39}$'),
  code text not null check (code ~ '^[a-z0-9][a-z0-9-]{0,79}$'),
  label text not null check (length(trim(label)) between 1 and 120),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (kind, code)
);

create unique index if not exists crm_catalog_items_kind_label_unique
  on public.crm_catalog_items (kind, lower(label));

create index if not exists crm_catalog_items_kind_active_sort
  on public.crm_catalog_items (kind, is_active, sort_order, label);

insert into public.crm_catalog_items (kind, code, label, sort_order, is_active)
values
  ('country', 'afghanistan', 'Afghanistan', 10, true),
  ('country', 'albania', 'Albania', 20, true),
  ('country', 'algeria', 'Algeria', 30, true),
  ('country', 'andorra', 'Andorra', 40, true),
  ('country', 'angola', 'Angola', 50, true),
  ('country', 'antigua-and-barbuda', 'Antigua and Barbuda', 60, true),
  ('country', 'argentina', 'Argentina', 70, true),
  ('country', 'armenia', 'Armenia', 80, true),
  ('country', 'australia', 'Australia', 90, true),
  ('country', 'austria', 'Austria', 100, true),
  ('country', 'azerbaijan', 'Azerbaijan', 110, true),
  ('country', 'bahamas', 'Bahamas', 120, true),
  ('country', 'bahrain', 'Bahrain', 130, true),
  ('country', 'bangladesh', 'Bangladesh', 140, true),
  ('country', 'barbados', 'Barbados', 150, true),
  ('country', 'belarus', 'Belarus', 160, true),
  ('country', 'belgium', 'Belgium', 170, true),
  ('country', 'belize', 'Belize', 180, true),
  ('country', 'benin', 'Benin', 190, true),
  ('country', 'bhutan', 'Bhutan', 200, true),
  ('country', 'bolivia', 'Bolivia', 210, true),
  ('country', 'bosnia-and-herzegovina', 'Bosnia and Herzegovina', 220, true),
  ('country', 'botswana', 'Botswana', 230, true),
  ('country', 'brazil', 'Brazil', 240, true),
  ('country', 'brunei', 'Brunei', 250, true),
  ('country', 'bulgaria', 'Bulgaria', 260, true),
  ('country', 'burkina-faso', 'Burkina Faso', 270, true),
  ('country', 'burundi', 'Burundi', 280, true),
  ('country', 'cambodia', 'Cambodia', 290, true),
  ('country', 'cameroon', 'Cameroon', 300, true),
  ('country', 'canada', 'Canada', 310, true),
  ('country', 'cape-verde', 'Cape Verde', 320, true),
  ('country', 'central-african-republic', 'Central African Republic', 330, true),
  ('country', 'chad', 'Chad', 340, true),
  ('country', 'chile', 'Chile', 350, true),
  ('country', 'china', 'China', 360, true),
  ('country', 'colombia', 'Colombia', 370, true),
  ('country', 'comoros', 'Comoros', 380, true),
  ('country', 'congo', 'Congo', 390, true),
  ('country', 'costa-rica', 'Costa Rica', 400, true),
  ('country', 'croatia', 'Croatia', 410, true),
  ('country', 'cuba', 'Cuba', 420, true),
  ('country', 'cyprus', 'Cyprus', 430, true),
  ('country', 'czech-republic', 'Czech Republic', 440, true),
  ('country', 'denmark', 'Denmark', 450, true),
  ('country', 'djibouti', 'Djibouti', 460, true),
  ('country', 'dominica', 'Dominica', 470, true),
  ('country', 'dominican-republic', 'Dominican Republic', 480, true),
  ('country', 'east-timor', 'East Timor', 490, true),
  ('country', 'ecuador', 'Ecuador', 500, true),
  ('country', 'egypt', 'Egypt', 510, true),
  ('country', 'el-salvador', 'El Salvador', 520, true),
  ('country', 'equatorial-guinea', 'Equatorial Guinea', 530, true),
  ('country', 'eritrea', 'Eritrea', 540, true),
  ('country', 'estonia', 'Estonia', 550, true),
  ('country', 'eswatini', 'Eswatini', 560, true),
  ('country', 'ethiopia', 'Ethiopia', 570, true),
  ('country', 'fiji', 'Fiji', 580, true),
  ('country', 'finland', 'Finland', 590, true),
  ('country', 'france', 'France', 600, true),
  ('country', 'gabon', 'Gabon', 610, true),
  ('country', 'gambia', 'Gambia', 620, true),
  ('country', 'georgia', 'Georgia', 630, true),
  ('country', 'germany', 'Germany', 640, true),
  ('country', 'ghana', 'Ghana', 650, true),
  ('country', 'greece', 'Greece', 660, true),
  ('country', 'grenada', 'Grenada', 670, true),
  ('country', 'guatemala', 'Guatemala', 680, true),
  ('country', 'guinea', 'Guinea', 690, true),
  ('country', 'guinea-bissau', 'Guinea-Bissau', 700, true),
  ('country', 'guyana', 'Guyana', 710, true),
  ('country', 'haiti', 'Haiti', 720, true),
  ('country', 'honduras', 'Honduras', 730, true),
  ('country', 'hungary', 'Hungary', 740, true),
  ('country', 'iceland', 'Iceland', 750, true),
  ('country', 'india', 'India', 760, true),
  ('country', 'indonesia', 'Indonesia', 770, true),
  ('country', 'iran', 'Iran', 780, true),
  ('country', 'iraq', 'Iraq', 790, true),
  ('country', 'ireland', 'Ireland', 800, true),
  ('country', 'israel', 'Israel', 810, true),
  ('country', 'italy', 'Italy', 820, true),
  ('country', 'ivory-coast', 'Ivory Coast', 830, true),
  ('country', 'jamaica', 'Jamaica', 840, true),
  ('country', 'japan', 'Japan', 850, true),
  ('country', 'jordan', 'Jordan', 860, true),
  ('country', 'kazakhstan', 'Kazakhstan', 870, true),
  ('country', 'kenya', 'Kenya', 880, true),
  ('country', 'kiribati', 'Kiribati', 890, true),
  ('country', 'kuwait', 'Kuwait', 900, true),
  ('country', 'kyrgyzstan', 'Kyrgyzstan', 910, true),
  ('country', 'laos', 'Laos', 920, true),
  ('country', 'latvia', 'Latvia', 930, true),
  ('country', 'lebanon', 'Lebanon', 940, true),
  ('country', 'lesotho', 'Lesotho', 950, true),
  ('country', 'liberia', 'Liberia', 960, true),
  ('country', 'libya', 'Libya', 970, true),
  ('country', 'liechtenstein', 'Liechtenstein', 980, true),
  ('country', 'lithuania', 'Lithuania', 990, true),
  ('country', 'luxembourg', 'Luxembourg', 1000, true),
  ('country', 'madagascar', 'Madagascar', 1010, true),
  ('country', 'malawi', 'Malawi', 1020, true),
  ('country', 'malaysia', 'Malaysia', 1030, true),
  ('country', 'maldives', 'Maldives', 1040, true),
  ('country', 'mali', 'Mali', 1050, true),
  ('country', 'malta', 'Malta', 1060, true),
  ('country', 'marshall-islands', 'Marshall Islands', 1070, true),
  ('country', 'mauritania', 'Mauritania', 1080, true),
  ('country', 'mauritius', 'Mauritius', 1090, true),
  ('country', 'mexico', 'Mexico', 1100, true),
  ('country', 'micronesia', 'Micronesia', 1110, true),
  ('country', 'moldova', 'Moldova', 1120, true),
  ('country', 'monaco', 'Monaco', 1130, true),
  ('country', 'mongolia', 'Mongolia', 1140, true),
  ('country', 'montenegro', 'Montenegro', 1150, true),
  ('country', 'morocco', 'Morocco', 1160, true),
  ('country', 'mozambique', 'Mozambique', 1170, true),
  ('country', 'myanmar', 'Myanmar', 1180, true),
  ('country', 'namibia', 'Namibia', 1190, true),
  ('country', 'nauru', 'Nauru', 1200, true),
  ('country', 'nepal', 'Nepal', 1210, true),
  ('country', 'netherlands', 'Netherlands', 1220, true),
  ('country', 'new-zealand', 'New Zealand', 1230, true),
  ('country', 'nicaragua', 'Nicaragua', 1240, true),
  ('country', 'niger', 'Niger', 1250, true),
  ('country', 'nigeria', 'Nigeria', 1260, true),
  ('country', 'north-korea', 'North Korea', 1270, true),
  ('country', 'north-macedonia', 'North Macedonia', 1280, true),
  ('country', 'norway', 'Norway', 1290, true),
  ('country', 'oman', 'Oman', 1300, true),
  ('country', 'pakistan', 'Pakistan', 1310, true),
  ('country', 'palau', 'Palau', 1320, true),
  ('country', 'palestine', 'Palestine', 1330, true),
  ('country', 'panama', 'Panama', 1340, true),
  ('country', 'papua-new-guinea', 'Papua New Guinea', 1350, true),
  ('country', 'paraguay', 'Paraguay', 1360, true),
  ('country', 'peru', 'Peru', 1370, true),
  ('country', 'philippines', 'Philippines', 1380, true),
  ('country', 'poland', 'Poland', 1390, true),
  ('country', 'portugal', 'Portugal', 1400, true),
  ('country', 'qatar', 'Qatar', 1410, true),
  ('country', 'romania', 'Romania', 1420, true),
  ('country', 'russia', 'Russia', 1430, true),
  ('country', 'rwanda', 'Rwanda', 1440, true),
  ('country', 'saint-kitts-and-nevis', 'Saint Kitts and Nevis', 1450, true),
  ('country', 'saint-lucia', 'Saint Lucia', 1460, true),
  ('country', 'saint-vincent-and-the-grenadines', 'Saint Vincent and the Grenadines', 1470, true),
  ('country', 'samoa', 'Samoa', 1480, true),
  ('country', 'san-marino', 'San Marino', 1490, true),
  ('country', 'sao-tome-and-principe', 'Sao Tome and Principe', 1500, true),
  ('country', 'saudi-arabia', 'Saudi Arabia', 1510, true),
  ('country', 'senegal', 'Senegal', 1520, true),
  ('country', 'serbia', 'Serbia', 1530, true),
  ('country', 'seychelles', 'Seychelles', 1540, true),
  ('country', 'sierra-leone', 'Sierra Leone', 1550, true),
  ('country', 'singapore', 'Singapore', 1560, true),
  ('country', 'slovakia', 'Slovakia', 1570, true),
  ('country', 'slovenia', 'Slovenia', 1580, true),
  ('country', 'solomon-islands', 'Solomon Islands', 1590, true),
  ('country', 'somalia', 'Somalia', 1600, true),
  ('country', 'south-africa', 'South Africa', 1610, true),
  ('country', 'south-korea', 'South Korea', 1620, true),
  ('country', 'south-sudan', 'South Sudan', 1630, true),
  ('country', 'spain', 'Spain', 1640, true),
  ('country', 'sri-lanka', 'Sri Lanka', 1650, true),
  ('country', 'sudan', 'Sudan', 1660, true),
  ('country', 'suriname', 'Suriname', 1670, true),
  ('country', 'sweden', 'Sweden', 1680, true),
  ('country', 'switzerland', 'Switzerland', 1690, true),
  ('country', 'syria', 'Syria', 1700, true),
  ('country', 'taiwan', 'Taiwan', 1710, true),
  ('country', 'tajikistan', 'Tajikistan', 1720, true),
  ('country', 'tanzania', 'Tanzania', 1730, true),
  ('country', 'thailand', 'Thailand', 1740, true),
  ('country', 'togo', 'Togo', 1750, true),
  ('country', 'tonga', 'Tonga', 1760, true),
  ('country', 'trinidad-and-tobago', 'Trinidad and Tobago', 1770, true),
  ('country', 'tunisia', 'Tunisia', 1780, true),
  ('country', 'turkey', 'Turkey', 1790, true),
  ('country', 'turkmenistan', 'Turkmenistan', 1800, true),
  ('country', 'tuvalu', 'Tuvalu', 1810, true),
  ('country', 'uganda', 'Uganda', 1820, true),
  ('country', 'ukraine', 'Ukraine', 1830, true),
  ('country', 'united-arab-emirates', 'United Arab Emirates', 1840, true),
  ('country', 'united-kingdom', 'United Kingdom', 1850, true),
  ('country', 'united-states', 'United States', 1860, true),
  ('country', 'uruguay', 'Uruguay', 1870, true),
  ('country', 'usa', 'USA', 1880, true),
  ('country', 'uk', 'UK', 1890, true),
  ('country', 'uzbekistan', 'Uzbekistan', 1900, true),
  ('country', 'vanuatu', 'Vanuatu', 1910, true),
  ('country', 'vatican-city', 'Vatican City', 1920, true),
  ('country', 'venezuela', 'Venezuela', 1930, true),
  ('country', 'vietnam', 'Vietnam', 1940, true),
  ('country', 'yemen', 'Yemen', 1950, true),
  ('country', 'zambia', 'Zambia', 1960, true),
  ('country', 'zimbabwe', 'Zimbabwe', 1970, true),
  ('country', 'other', 'Other', 1980, true)
on conflict (kind, code) do nothing;

insert into public.crm_catalog_items (kind, code, label, sort_order, is_active)
values
  ('nationality', 'afghan', 'Afghan', 10, true),
  ('nationality', 'albanian', 'Albanian', 20, true),
  ('nationality', 'algerian', 'Algerian', 30, true),
  ('nationality', 'american', 'American', 40, true),
  ('nationality', 'andorran', 'Andorran', 50, true),
  ('nationality', 'angolan', 'Angolan', 60, true),
  ('nationality', 'antiguan', 'Antiguan', 70, true),
  ('nationality', 'argentine', 'Argentine', 80, true),
  ('nationality', 'armenian', 'Armenian', 90, true),
  ('nationality', 'australian', 'Australian', 100, true),
  ('nationality', 'austrian', 'Austrian', 110, true),
  ('nationality', 'azerbaijani', 'Azerbaijani', 120, true),
  ('nationality', 'bahamian', 'Bahamian', 130, true),
  ('nationality', 'bahraini', 'Bahraini', 140, true),
  ('nationality', 'bangladeshi', 'Bangladeshi', 150, true),
  ('nationality', 'barbadian', 'Barbadian', 160, true),
  ('nationality', 'belarusian', 'Belarusian', 170, true),
  ('nationality', 'belgian', 'Belgian', 180, true),
  ('nationality', 'belizean', 'Belizean', 190, true),
  ('nationality', 'beninese', 'Beninese', 200, true),
  ('nationality', 'bhutanese', 'Bhutanese', 210, true),
  ('nationality', 'bolivian', 'Bolivian', 220, true),
  ('nationality', 'bosnian', 'Bosnian', 230, true),
  ('nationality', 'botswanan', 'Botswanan', 240, true),
  ('nationality', 'brazilian', 'Brazilian', 250, true),
  ('nationality', 'british', 'British', 260, true),
  ('nationality', 'bruneian', 'Bruneian', 270, true),
  ('nationality', 'bulgarian', 'Bulgarian', 280, true),
  ('nationality', 'burkinabe', 'Burkinabe', 290, true),
  ('nationality', 'burmese', 'Burmese', 300, true),
  ('nationality', 'burundian', 'Burundian', 310, true),
  ('nationality', 'cambodian', 'Cambodian', 320, true),
  ('nationality', 'cameroonian', 'Cameroonian', 330, true),
  ('nationality', 'canadian', 'Canadian', 340, true),
  ('nationality', 'cape-verdean', 'Cape Verdean', 350, true),
  ('nationality', 'central-african', 'Central African', 360, true),
  ('nationality', 'chadian', 'Chadian', 370, true),
  ('nationality', 'chilean', 'Chilean', 380, true),
  ('nationality', 'chinese', 'Chinese', 390, true),
  ('nationality', 'colombian', 'Colombian', 400, true),
  ('nationality', 'comoran', 'Comoran', 410, true),
  ('nationality', 'congolese', 'Congolese', 420, true),
  ('nationality', 'costa-rican', 'Costa Rican', 430, true),
  ('nationality', 'croatian', 'Croatian', 440, true),
  ('nationality', 'cuban', 'Cuban', 450, true),
  ('nationality', 'cypriot', 'Cypriot', 460, true),
  ('nationality', 'czech', 'Czech', 470, true),
  ('nationality', 'danish', 'Danish', 480, true),
  ('nationality', 'djiboutian', 'Djiboutian', 490, true),
  ('nationality', 'dominican', 'Dominican', 500, true),
  ('nationality', 'dutch', 'Dutch', 510, true),
  ('nationality', 'east-timorese', 'East Timorese', 520, true),
  ('nationality', 'ecuadorean', 'Ecuadorean', 530, true),
  ('nationality', 'egyptian', 'Egyptian', 540, true),
  ('nationality', 'emirati', 'Emirati', 550, true),
  ('nationality', 'equatorial-guinean', 'Equatorial Guinean', 560, true),
  ('nationality', 'eritrean', 'Eritrean', 570, true),
  ('nationality', 'estonian', 'Estonian', 580, true),
  ('nationality', 'ethiopian', 'Ethiopian', 590, true),
  ('nationality', 'fijian', 'Fijian', 600, true),
  ('nationality', 'finnish', 'Finnish', 610, true),
  ('nationality', 'french', 'French', 620, true),
  ('nationality', 'gabonese', 'Gabonese', 630, true),
  ('nationality', 'gambian', 'Gambian', 640, true),
  ('nationality', 'georgian', 'Georgian', 650, true),
  ('nationality', 'german', 'German', 660, true),
  ('nationality', 'ghanaian', 'Ghanaian', 670, true),
  ('nationality', 'greek', 'Greek', 680, true),
  ('nationality', 'grenadian', 'Grenadian', 690, true),
  ('nationality', 'guatemalan', 'Guatemalan', 700, true),
  ('nationality', 'guinean', 'Guinean', 710, true),
  ('nationality', 'guyanese', 'Guyanese', 720, true),
  ('nationality', 'haitian', 'Haitian', 730, true),
  ('nationality', 'honduran', 'Honduran', 740, true),
  ('nationality', 'hungarian', 'Hungarian', 750, true),
  ('nationality', 'icelandic', 'Icelandic', 760, true),
  ('nationality', 'indian', 'Indian', 770, true),
  ('nationality', 'indonesian', 'Indonesian', 780, true),
  ('nationality', 'iranian', 'Iranian', 790, true),
  ('nationality', 'iraqi', 'Iraqi', 800, true),
  ('nationality', 'irish', 'Irish', 810, true),
  ('nationality', 'israeli', 'Israeli', 820, true),
  ('nationality', 'italian', 'Italian', 830, true),
  ('nationality', 'ivorian', 'Ivorian', 840, true),
  ('nationality', 'jamaican', 'Jamaican', 850, true),
  ('nationality', 'japanese', 'Japanese', 860, true),
  ('nationality', 'jordanian', 'Jordanian', 870, true),
  ('nationality', 'kazakh', 'Kazakh', 880, true),
  ('nationality', 'kenyan', 'Kenyan', 890, true),
  ('nationality', 'kuwaiti', 'Kuwaiti', 900, true),
  ('nationality', 'kyrgyz', 'Kyrgyz', 910, true),
  ('nationality', 'laotian', 'Laotian', 920, true),
  ('nationality', 'latvian', 'Latvian', 930, true),
  ('nationality', 'lebanese', 'Lebanese', 940, true),
  ('nationality', 'liberian', 'Liberian', 950, true),
  ('nationality', 'libyan', 'Libyan', 960, true),
  ('nationality', 'liechtensteiner', 'Liechtensteiner', 970, true),
  ('nationality', 'lithuanian', 'Lithuanian', 980, true),
  ('nationality', 'luxembourger', 'Luxembourger', 990, true),
  ('nationality', 'macedonian', 'Macedonian', 1000, true),
  ('nationality', 'malagasy', 'Malagasy', 1010, true),
  ('nationality', 'malawian', 'Malawian', 1020, true),
  ('nationality', 'malaysian', 'Malaysian', 1030, true),
  ('nationality', 'maldivian', 'Maldivian', 1040, true),
  ('nationality', 'malian', 'Malian', 1050, true),
  ('nationality', 'maltese', 'Maltese', 1060, true),
  ('nationality', 'marshallese', 'Marshallese', 1070, true),
  ('nationality', 'mauritanian', 'Mauritanian', 1080, true),
  ('nationality', 'mauritian', 'Mauritian', 1090, true),
  ('nationality', 'mexican', 'Mexican', 1100, true),
  ('nationality', 'micronesian', 'Micronesian', 1110, true),
  ('nationality', 'moldovan', 'Moldovan', 1120, true),
  ('nationality', 'monacan', 'Monacan', 1130, true),
  ('nationality', 'mongolian', 'Mongolian', 1140, true),
  ('nationality', 'montenegrin', 'Montenegrin', 1150, true),
  ('nationality', 'moroccan', 'Moroccan', 1160, true),
  ('nationality', 'mozambican', 'Mozambican', 1170, true),
  ('nationality', 'namibian', 'Namibian', 1180, true),
  ('nationality', 'nauruan', 'Nauruan', 1190, true),
  ('nationality', 'nepalese', 'Nepalese', 1200, true),
  ('nationality', 'new-zealander', 'New Zealander', 1210, true),
  ('nationality', 'nicaraguan', 'Nicaraguan', 1220, true),
  ('nationality', 'nigerian', 'Nigerian', 1230, true),
  ('nationality', 'nigerien', 'Nigerien', 1240, true),
  ('nationality', 'north-korean', 'North Korean', 1250, true),
  ('nationality', 'norwegian', 'Norwegian', 1260, true),
  ('nationality', 'omani', 'Omani', 1270, true),
  ('nationality', 'pakistani', 'Pakistani', 1280, true),
  ('nationality', 'palauan', 'Palauan', 1290, true),
  ('nationality', 'palestinian', 'Palestinian', 1300, true),
  ('nationality', 'panamanian', 'Panamanian', 1310, true),
  ('nationality', 'papua-new-guinean', 'Papua New Guinean', 1320, true),
  ('nationality', 'paraguayan', 'Paraguayan', 1330, true),
  ('nationality', 'peruvian', 'Peruvian', 1340, true),
  ('nationality', 'filipino', 'Filipino', 1350, true),
  ('nationality', 'polish', 'Polish', 1360, true),
  ('nationality', 'portuguese', 'Portuguese', 1370, true),
  ('nationality', 'qatari', 'Qatari', 1380, true),
  ('nationality', 'romanian', 'Romanian', 1390, true),
  ('nationality', 'russian', 'Russian', 1400, true),
  ('nationality', 'rwandan', 'Rwandan', 1410, true),
  ('nationality', 'saint-lucian', 'Saint Lucian', 1420, true),
  ('nationality', 'salvadoran', 'Salvadoran', 1430, true),
  ('nationality', 'samoan', 'Samoan', 1440, true),
  ('nationality', 'san-marinese', 'San Marinese', 1450, true),
  ('nationality', 'sao-tomean', 'Sao Tomean', 1460, true),
  ('nationality', 'saudi', 'Saudi', 1470, true),
  ('nationality', 'scottish', 'Scottish', 1480, true),
  ('nationality', 'senegalese', 'Senegalese', 1490, true),
  ('nationality', 'serbian', 'Serbian', 1500, true),
  ('nationality', 'seychellois', 'Seychellois', 1510, true),
  ('nationality', 'sierra-leonean', 'Sierra Leonean', 1520, true),
  ('nationality', 'singaporean', 'Singaporean', 1530, true),
  ('nationality', 'slovak', 'Slovak', 1540, true),
  ('nationality', 'slovenian', 'Slovenian', 1550, true),
  ('nationality', 'solomon-islander', 'Solomon Islander', 1560, true),
  ('nationality', 'somali', 'Somali', 1570, true),
  ('nationality', 'south-african', 'South African', 1580, true),
  ('nationality', 'south-korean', 'South Korean', 1590, true),
  ('nationality', 'spanish', 'Spanish', 1600, true),
  ('nationality', 'sri-lankan', 'Sri Lankan', 1610, true),
  ('nationality', 'sudanese', 'Sudanese', 1620, true),
  ('nationality', 'surinamese', 'Surinamese', 1630, true),
  ('nationality', 'swazi', 'Swazi', 1640, true),
  ('nationality', 'swedish', 'Swedish', 1650, true),
  ('nationality', 'swiss', 'Swiss', 1660, true),
  ('nationality', 'syrian', 'Syrian', 1670, true),
  ('nationality', 'taiwanese', 'Taiwanese', 1680, true),
  ('nationality', 'tajik', 'Tajik', 1690, true),
  ('nationality', 'tanzanian', 'Tanzanian', 1700, true),
  ('nationality', 'thai', 'Thai', 1710, true),
  ('nationality', 'togolese', 'Togolese', 1720, true),
  ('nationality', 'tongan', 'Tongan', 1730, true),
  ('nationality', 'trinidadian', 'Trinidadian', 1740, true),
  ('nationality', 'tunisian', 'Tunisian', 1750, true),
  ('nationality', 'turkish', 'Turkish', 1760, true),
  ('nationality', 'turkmen', 'Turkmen', 1770, true),
  ('nationality', 'tuvaluan', 'Tuvaluan', 1780, true),
  ('nationality', 'ugandan', 'Ugandan', 1790, true),
  ('nationality', 'ukrainian', 'Ukrainian', 1800, true),
  ('nationality', 'uruguayan', 'Uruguayan', 1810, true),
  ('nationality', 'uzbek', 'Uzbek', 1820, true),
  ('nationality', 'vanuatuan', 'Vanuatuan', 1830, true),
  ('nationality', 'venezuelan', 'Venezuelan', 1840, true),
  ('nationality', 'vietnamese', 'Vietnamese', 1850, true),
  ('nationality', 'welsh', 'Welsh', 1860, true),
  ('nationality', 'yemeni', 'Yemeni', 1870, true),
  ('nationality', 'zambian', 'Zambian', 1880, true),
  ('nationality', 'zimbabwean', 'Zimbabwean', 1890, true)
on conflict (kind, code) do nothing;

insert into public.crm_catalog_items (kind, code, label, sort_order, is_active)
values
  ('customer_source', 'referral', 'Referral', 10, true),
  ('customer_source', 'website', 'Website', 20, true),
  ('customer_source', 'agent', 'Agent', 30, true),
  ('customer_source', 'virtuoso', 'Virtuoso', 40, true),
  ('customer_source', 'abercrombie', 'Abercrombie', 50, true),
  ('customer_source', 'social-media', 'Social Media', 60, true),
  ('customer_source', 'walk-in', 'Walk-in', 70, true),
  ('customer_source', 'direct', 'Direct', 80, true)
on conflict (kind, code) do nothing;

insert into public.crm_catalog_items (kind, code, label, sort_order, is_active)
values
  ('customer_language', 'english', 'English', 10, true),
  ('customer_language', 'french', 'French', 20, true),
  ('customer_language', 'german', 'German', 30, true),
  ('customer_language', 'spanish', 'Spanish', 40, true),
  ('customer_language', 'italian', 'Italian', 50, true)
on conflict (kind, code) do nothing;

insert into public.crm_catalog_items (kind, code, label, sort_order, is_active)
values
  ('customer_budget', 'under-1000pax', 'Under $1,000/pax', 10, true),
  ('customer_budget', '10002000pax', '$1,000–$2,000/pax', 20, true),
  ('customer_budget', '20003500pax', '$2,000–$3,500/pax', 30, true),
  ('customer_budget', '35006000pax', '$3,500–$6,000/pax', 40, true),
  ('customer_budget', '6000pax', '$6,000+/pax', 50, true)
on conflict (kind, code) do nothing;

insert into public.crm_catalog_items (kind, code, label, sort_order, is_active)
values
  ('salesperson', 'tai-pham', 'Tai Pham', 10, true),
  ('salesperson', 'linh-n', 'Linh N.', 20, true),
  ('salesperson', 'minh-t', 'Minh T.', 30, true),
  ('salesperson', 'huong-l', 'Huong L.', 40, true),
  ('salesperson', 'khoa-v', 'Khoa V.', 50, true)
on conflict (kind, code) do nothing;


-- Permissions
insert into public.permission_groups (code, label, sort_order, page_slug, is_navigation_feature)
values ('settings', 'Cài đặt', 205, 'settings', true)
on conflict (code) do update
set
  label = excluded.label,
  sort_order = excluded.sort_order,
  page_slug = excluded.page_slug,
  is_navigation_feature = excluded.is_navigation_feature;

insert into public.permissions (code, description, group_code)
values
  ('settings.read', 'Xem cài đặt hệ thống / danh mục', 'settings'),
  ('settings.write', 'Sửa cài đặt hệ thống / danh mục', 'settings')
on conflict (code) do update
set
  description = excluded.description,
  group_code = excluded.group_code;

insert into public.role_permissions (role_code, permission_code)
select 'admin', p.code
from public.permissions p
where p.code in ('settings.read', 'settings.write')
on conflict do nothing;

alter table public.crm_catalog_items enable row level security;
revoke all on table public.crm_catalog_items from anon, authenticated;
grant select, insert, update, delete on table public.crm_catalog_items to authenticated;

drop policy if exists rls_crm_catalog_items_select on public.crm_catalog_items;
drop policy if exists rls_crm_catalog_items_insert on public.crm_catalog_items;
drop policy if exists rls_crm_catalog_items_update on public.crm_catalog_items;
drop policy if exists rls_crm_catalog_items_delete on public.crm_catalog_items;

create policy rls_crm_catalog_items_select on public.crm_catalog_items
  for select to authenticated using (
    public.has_permission('settings.read')
    or public.has_permission('customers.read')
    or public.has_permission('customers.write')
    or public.has_permission('tour_design.read')
  );

create policy rls_crm_catalog_items_insert on public.crm_catalog_items
  for insert to authenticated with check (public.has_permission('settings.write'));

create policy rls_crm_catalog_items_update on public.crm_catalog_items
  for update to authenticated
  using (public.has_permission('settings.write'))
  with check (public.has_permission('settings.write'));

create policy rls_crm_catalog_items_delete on public.crm_catalog_items
  for delete to authenticated using (public.has_permission('settings.write'));
